import { GoogleGenerativeAI } from "@google/generative-ai";
import models from "../models/index.js";

const { PronunciationTask, StudentAttempt } = models;

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

const createTask = async (req, res) => {
  try {
    const { title, instruction, expected_text } = req.body;
    const task = await PronunciationTask.create({ title, instruction, expected_text });
    res.status(201).json(task);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Failed to create task" });
  }
};

const getTasks = async (req, res) => {
  try {
    const tasks = await PronunciationTask.findAll();
    res.status(200).json(tasks);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Failed to fetch tasks" });
  }
};

const updateTask = async (req, res) => {
  try {
    const { id } = req.params;
    const { title, instruction, expected_text } = req.body;
    const task = await PronunciationTask.findByPk(id);
    if (!task) return res.status(404).json({ error: "Task not found" });
    
    await task.update({ title, instruction, expected_text });
    res.status(200).json(task);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Failed to update task" });
  }
};

const deleteTask = async (req, res) => {
  try {
    const { id } = req.params;
    const task = await PronunciationTask.findByPk(id);
    if (!task) return res.status(404).json({ error: "Task not found" });
    
    await task.destroy();
    res.status(200).json({ message: "Task deleted successfully" });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Failed to delete task" });
  }
};

const evaluateAttempt = async (req, res) => {
  try {
    const { task_id, transcribed_text, student_id, sentence_index } = req.body;

    const task = await PronunciationTask.findByPk(task_id);
    if (!task) {
      return res.status(404).json({ error: "Task not found" });
    }

    let expectedText = task.expected_text;
    
    // If expected_text is an array and a sentence_index is provided, evaluate only that sentence
    if (Array.isArray(expectedText)) {
      if (sentence_index !== undefined && expectedText[sentence_index]) {
        expectedText = expectedText[sentence_index];
      } else {
        expectedText = expectedText.join(' ');
      }
    }

    // Use Gemini
    const model = genAI.getGenerativeModel({ model: "gemini-flash-latest", generationConfig: { responseMimeType: "application/json" } });

    const prompt = `
      You are an expert English pronunciation evaluator.
      Compare the "expected_text" with the "transcribed_text" (which is generated by a speech-to-text engine).
      Identify omitted words or mispronounced words.
      If a word in the expected text does not appear in the transcribed text, or appears as a completely different word (phonetically dissimilar), mark it as an error.

      Expected Text: "${expectedText}"
      Transcribed Text: "${transcribed_text}"

      Return strictly a JSON object with this exact structure:
      {
        "score": <number 0-100>,
        "errors": [
          { "word": "<word from expected text>", "reason": "omitted" | "mispronounced as '<what they said>'" }
        ]
      }
    `;

    const result = await model.generateContent(prompt);
    const responseText = result.response.text();
    let evaluationResult;
    try {
      const cleanText = responseText.replace(/```json/gi, '').replace(/```/g, '').trim();
      evaluationResult = JSON.parse(cleanText);
    } catch (e) {
      console.error("Failed to parse JSON from Gemini:", responseText);
      return res.status(500).json({ error: "Invalid response from AI evaluator" });
    }

    const attempt = await StudentAttempt.create({
      student_id: student_id || null,
      task_id,
      sentence_index,
      transcribed_text,
      score: evaluationResult.score,
      feedback_json: evaluationResult.errors
    });

    res.status(200).json({ attempt, evaluation: evaluationResult });
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Failed to evaluate attempt" });
  }
};

const getLeaderboard = async (req, res) => {
  try {
    const { Op } = require("sequelize");
    const sequelize = models.StudentAttempt.sequelize;
    const startOfMonth = new Date();
    startOfMonth.setDate(1);
    startOfMonth.setHours(0, 0, 0, 0);

    const leaderboard = await StudentAttempt.findAll({
      attributes: [
        'student_id',
        [sequelize.fn('SUM', sequelize.col('score')), 'total_score']
      ],
      where: {
        createdAt: {
          [Op.gte]: startOfMonth
        },
        student_id: {
          [Op.ne]: null
        }
      },
      group: ['student_id', 'user.id'],
      include: [{
        model: models.user,
        attributes: ['name', 'email']
      }],
      order: [[sequelize.literal('total_score'), 'DESC']],
      limit: 10
    });

    res.status(200).json(leaderboard);
  } catch (error) {
    console.error(error);
    res.status(500).json({ error: "Failed to fetch leaderboard" });
  }
};

export default {
  createTask,
  getTasks,
  updateTask,
  deleteTask,
  evaluateAttempt,
  getLeaderboard
};
